spring.datasource.type: "com.zaxxer.hikari.HikariDataSource"

spring:
  application:
    name: terraform
  datasource:
      driverClassName: "com.mysql.cj.jdbc.Driver"
      url: "jdbc:mysql://127.0.0.1:3306/sys?serverTimezone=GMT&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true"
      username: "admin"
      password: "admin"
  redis:
    host: 127.0.0.1
    password:
    port: 6379
#    redisson:
#      #Redisson配置
#      singleServerConfig:
#        address: "redis://127.0.0.1:6379"
#        password: null
#        clientName: null
#        database: 1 #选择使用哪个数据库0~15
#        idleConnectionTimeout: 10000
#        pingTimeout: 1000
#        connectTimeout: 10000
#        timeout: 3000
#        retryAttempts: 3
#        retryInterval: 1500
#        reconnectionTimeout: 3000
#        failedAttempts: 3
#        subscriptionsPerConnection: 5
#        subscriptionConnectionMinimumIdleSize: 1
#        subscriptionConnectionPoolSize: 50
#        connectionMinimumIdleSize: 32
#        connectionPoolSize: 64
#        dnsMonitoringInterval: 5000
#        #dnsMonitoring: false
#      threads: 0
#      nettyThreads: 0
#      codec:
#        class: "org.redisson.codec.JsonJacksonCodec"
#      transportMode: "NIO"

server:
  port: 8083

mybatis:
  #  config-location: classpath:conf/mybatis-config.xml  相对于resources文件夹的路径
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.terraform.model

logging.level.org.springframework: debug
logging:
  level:
    com:
      terraform:
            repository: debug



